language: csharp
solution: Challenge.sln
install:
  - nuget restore Challenge.sln
  - nuget install NUnit.Runners -Version 3.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release Challenge.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./Challenge.Tests/bin/Release/Challenge.Tests.dll